# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a75f0215927d1fc06c1d6beb9403707d5a16e3c7836bdb06933f820f635aa5a816c2b74e85d504cb85546308544c32fc65275330b94ad47b9ecfa2c453be96

test:
  secret_key_base: 38927fcafd2bb62a676e746c87d1ccd98a7bf1a24c3fc60a4b87c4324525bb6ffa3f4487ccc34e87e64c419812c717815924b4e583ef3ae4a8559096dbc3d219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
